export default {
  type: '',
  permits: [],
  editModules: {
    checkedList: [],
    children: [{
      name: '产品信息',
      value: '产品信息'
    }, {
      name: '资产信息',
      value: '资产信息'
    }, {
      name: '资金账户信息',
      value: '资金账户信息'
    }, {
      name: '审批流程信息',
      value: '审批流程信息'
    }, {
      name: '公司账户信息',
      value: '公司账户信息'
    }]
  },
  deleteModules: {
    checkedList: [],
    children: [{
      name: '产品信息',
      value: '产品信息'
    }, {
      name: '资产信息',
      value: '资产信息'
    }, {
      name: '资金账户信息',
      value: '资金账户信息'
    }, {
      name: '审批流程信息',
      value: '审批流程信息'
    }, {
      name: '公司账户信息',
      value: '公司账户信息'
    }]
  },
  checkModules: [{
    name: '总览页',
    value: '总览页',
    checkedList: [],
    checked: false,
    indeterminate: true,
    children: [{
      name: '存续金额模块',
      value: '存续金额模块'
    }, {
      name: '占比分析模块',
      value: '占比分析模块'
    }, {
      name: '当前状态模块',
      value: '当前状态模块'
    }, {
      name: '日历模块',
      value: '日历模块'
    }, {
      name: '趋势图模块',
      value: '趋势图模块'
    }]
  }, {
    name: '产品总列表页',
    value: '产品总列表页',
    checkedList: [],
    checked: false,
    indeterminate: true,
    children: []
  }, {
    name: '登记产品总列表页',
    value: '登记产品总列表页',
    checkedList: [],
    checked: false,
    indeterminate: true,
    children: []
  }, {
    name: '产品详情页',
    value: '产品详情页',
    checkedList: [],
    checked: false,
    indeterminate: true,
    children: [{
      name: '附件',
      value: '附件'
    }, {
      name: '待办事项-资金',
      value: '待办事项-资金'
    }, {
      name: ' 待办事项-资产',
      value: ' 待办事项-资产'
    }, {
      name: '持仓详情',
      value: '持仓详情'
    }, {
      name: '客户列表',
      value: '客户列表'
    }, {
      name: '登记产品列表',
      value: '登记产品列表'
    }, {
      name: '费用详情',
      value: '费用详情'
    }]
  }, {
    name: '资产总列表',
    value: '资产总列表',
    checkedList: [],
    checked: false,
    indeterminate: true,
    children: []
  }, {
    name: '资产详情页',
    value: '资产详情页',
    checkedList: [],
    checked: false,
    indeterminate: true,
    children: [{
      name: '附件',
      value: '附件'
    }, {
      name: '基础信息与备注',
      value: '基础信息与备注'
    }, {
      name: '持有产品列表',
      value: '持有产品列表'
    }, {
      name: '待办事项',
      value: '待办事项'
    }, {
      name: '行情信息',
      value: '行情信息'
    }, {
      name: '平台列表页',
      value: '平台列表页',
      children: []
    }, {
      name: '客户列表',
      value: '客户列表',
      children: []
    }]
  }]
}
